- name: Ping the server
  hosts: frontend #inventory ki velli frontend group lo unna servers annitiki cover chesthundhi

  #list of tasks/collections/modules
  tasks:
  - name: ping
    ansible.builtin.ping:
    